#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
HOST="${ACUIFERO_API_HOST:-0.0.0.0}"
PORT="${ACUIFERO_API_PORT:-8000}"

export ACUIFERO_NODE_PROFILE="${ACUIFERO_NODE_PROFILE:-raspberry-pi-8gb-multimodal-demo}"
export ACUIFERO_DATA_DIR="${ACUIFERO_DATA_DIR:-/mnt/acuifero/data}"
export ACUIFERO_NODE_PROVIDER="${ACUIFERO_NODE_PROVIDER:-litert}"
export ACUIFERO_NODE_MODEL_PATH="${ACUIFERO_NODE_MODEL_PATH:-$BACKEND_DIR/data/models/gemma-4-E2B-it.litertlm}"
export ACUIFERO_NODE_BACKEND="${ACUIFERO_NODE_BACKEND:-gpu}"
export ACUIFERO_NODE_MULTIMODAL_BACKEND="${ACUIFERO_NODE_MULTIMODAL_BACKEND:-cpu}"
export ACUIFERO_NODE_MULTIMODAL_VISION_BACKEND="${ACUIFERO_NODE_MULTIMODAL_VISION_BACKEND:-cpu}"
export ACUIFERO_NODE_CACHE_DIR="${ACUIFERO_NODE_CACHE_DIR:-$BACKEND_DIR/data/litert-cache}"
export ACUIFERO_NODE_ENABLE_SPECULATIVE_DECODING="${ACUIFERO_NODE_ENABLE_SPECULATIVE_DECODING:-true}"
export ACUIFERO_NODE_MAX_OUTPUT_TOKENS="${ACUIFERO_NODE_MAX_OUTPUT_TOKENS:-1024}"
export ACUIFERO_NODE_MULTIMODAL_MAX_OUTPUT_TOKENS="${ACUIFERO_NODE_MULTIMODAL_MAX_OUTPUT_TOKENS:-2048}"
export ACUIFERO_LLM_ENABLED="${ACUIFERO_LLM_ENABLED:-true}"
export ACUIFERO_LLM_BASE_URL="${ACUIFERO_LLM_BASE_URL:-http://127.0.0.1:11434/v1}"
export ACUIFERO_LLM_MODEL="${ACUIFERO_LLM_MODEL:-gemma4:e2b}"
export ACUIFERO_LLM_API_KEY="${ACUIFERO_LLM_API_KEY:-ollama}"

export ACUIFERO_MULTIMODAL_ENABLED="${ACUIFERO_MULTIMODAL_ENABLED:-true}"
export ACUIFERO_MULTIMODAL_VERIFIER_ENABLED="${ACUIFERO_MULTIMODAL_VERIFIER_ENABLED:-false}"
export ACUIFERO_MULTIMODAL_BASE_URL="${ACUIFERO_MULTIMODAL_BASE_URL:-$ACUIFERO_LLM_BASE_URL}"
export ACUIFERO_MULTIMODAL_MODEL="${ACUIFERO_MULTIMODAL_MODEL:-gemma4:e2b}"
export ACUIFERO_MULTIMODAL_MAX_FRAMES="${ACUIFERO_MULTIMODAL_MAX_FRAMES:-1}"
export ACUIFERO_MULTIMODAL_FRAME_SAMPLE_SECONDS="${ACUIFERO_MULTIMODAL_FRAME_SAMPLE_SECONDS:-300}"
export ACUIFERO_MULTIMODAL_IMAGE_MAX_SIDE="${ACUIFERO_MULTIMODAL_IMAGE_MAX_SIDE:-512}"
export ACUIFERO_MULTIMODAL_NUM_CTX="${ACUIFERO_MULTIMODAL_NUM_CTX:-1024}"
export ACUIFERO_MULTIMODAL_NUM_PREDICT="${ACUIFERO_MULTIMODAL_NUM_PREDICT:-192}"
export ACUIFERO_MULTIMODAL_TIMEOUT_SECONDS="${ACUIFERO_MULTIMODAL_TIMEOUT_SECONDS:-300}"

export ACUIFERO_MAX_CURATED_FRAMES="${ACUIFERO_MAX_CURATED_FRAMES:-1}"
export ACUIFERO_ARTIFACT_RETENTION_DAYS="${ACUIFERO_ARTIFACT_RETENTION_DAYS:-3}"

cd "$BACKEND_DIR"
if [[ -d ".venv" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
else
  echo "Missing backend virtualenv at $BACKEND_DIR/.venv" >&2
  exit 1
fi

python3 "$ROOT_DIR/scripts/fetch_litert_model.py"
python3 "$ROOT_DIR/scripts/fetch_demo_assets.py"
PYTHONPATH=src python3 -m acuifero_vigia.scripts.seed
PYTHONPATH=src python3 -m uvicorn acuifero_vigia.main:app --host "$HOST" --port "$PORT"
