#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
HOST="${ACUIFERO_API_HOST:-0.0.0.0}"
PORT="${ACUIFERO_API_PORT:-8000}"

export ACUIFERO_NODE_PROFILE="${ACUIFERO_NODE_PROFILE:-raspberry-pi-8gb-hybrid}"
export ACUIFERO_DATA_DIR="${ACUIFERO_DATA_DIR:-/mnt/acuifero/data}"
export ACUIFERO_LLM_ENABLED="${ACUIFERO_LLM_ENABLED:-true}"
export ACUIFERO_LLM_BASE_URL="${ACUIFERO_LLM_BASE_URL:-http://127.0.0.1:11434/v1}"
export ACUIFERO_LLM_MODEL="${ACUIFERO_LLM_MODEL:-gemma4:e2b}"
export ACUIFERO_LLM_API_KEY="${ACUIFERO_LLM_API_KEY:-ollama}"

# Primary node assessment stays text-first on Raspberry Pi 8 GB. OpenCV is the
# always-on visual worker; Gemma 4 multimodal only verifies one curated frame.
export ACUIFERO_MULTIMODAL_ENABLED="${ACUIFERO_MULTIMODAL_ENABLED:-false}"
export ACUIFERO_MULTIMODAL_VERIFIER_ENABLED="${ACUIFERO_MULTIMODAL_VERIFIER_ENABLED:-true}"
export ACUIFERO_MULTIMODAL_BASE_URL="${ACUIFERO_MULTIMODAL_BASE_URL:-$ACUIFERO_LLM_BASE_URL}"
export ACUIFERO_MULTIMODAL_MODEL="${ACUIFERO_MULTIMODAL_MODEL:-gemma4:e2b}"
export ACUIFERO_MULTIMODAL_MIN_INTERVAL_SECONDS="${ACUIFERO_MULTIMODAL_MIN_INTERVAL_SECONDS:-300}"
export ACUIFERO_MULTIMODAL_SCORE_THRESHOLD="${ACUIFERO_MULTIMODAL_SCORE_THRESHOLD:-0.55}"
export ACUIFERO_MULTIMODAL_CONFIDENCE_THRESHOLD="${ACUIFERO_MULTIMODAL_CONFIDENCE_THRESHOLD:-0.62}"
export ACUIFERO_MULTIMODAL_IMAGE_MAX_SIDE="${ACUIFERO_MULTIMODAL_IMAGE_MAX_SIDE:-768}"
export ACUIFERO_MULTIMODAL_NUM_CTX="${ACUIFERO_MULTIMODAL_NUM_CTX:-2048}"
export ACUIFERO_MULTIMODAL_NUM_PREDICT="${ACUIFERO_MULTIMODAL_NUM_PREDICT:-256}"
export ACUIFERO_MULTIMODAL_TIMEOUT_SECONDS="${ACUIFERO_MULTIMODAL_TIMEOUT_SECONDS:-180}"

export ACUIFERO_MAX_CURATED_FRAMES="${ACUIFERO_MAX_CURATED_FRAMES:-3}"
export ACUIFERO_ARTIFACT_RETENTION_DAYS="${ACUIFERO_ARTIFACT_RETENTION_DAYS:-7}"

"$ROOT_DIR/scripts/run_gemma_local.sh" "$ACUIFERO_LLM_MODEL"
if [[ "$ACUIFERO_MULTIMODAL_MODEL" != "$ACUIFERO_LLM_MODEL" ]]; then
  "$ROOT_DIR/scripts/run_gemma_local.sh" "$ACUIFERO_MULTIMODAL_MODEL"
fi

cd "$BACKEND_DIR"
if [[ -d ".venv" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi

PYTHONPATH=src python3 -m acuifero_vigia.scripts.seed
PYTHONPATH=src python3 -m uvicorn acuifero_vigia.main:app --host "$HOST" --port "$PORT"
